import React from 'react'

const Internal = () => {
  return (
    <div className='midSections pd'>
      <h1>Internal Research</h1>
      <p>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat ipsum animi iure rerum tenetur blanditiis, perspiciatis sed, molestias itaque error illo ullam saepe sequi dolorum reiciendis quam corrupti quos quisquam nemo dicta aliquam culpa. Nam repellendus recusandae veniam suscipit minima odit laborum animi dolorum quibusdam error accusamus architecto maiores, fuga dolor est quas aliquid voluptatem natus molestiae, voluptas quod fugiat voluptate eum. Impedit numquam mollitia voluptates aspernatur dolor cum inventore architecto ratione. Ducimus suscipit nisi optio alias dolor voluptates ipsum natus, placeat unde, tenetur aliquam, temporibus quis neque cum magni vitae vero? Repudiandae, dolorem! Error suscipit maxime nemo? Mollitia eveniet dolore repellat eos animi fugit cupiditate unde praesentium sunt laudantium dignissimos aperiam ipsum, dolor, ea cumque qui excepturi ad voluptate rerum. Reprehenderit iste esse omnis vero voluptates. Neque soluta at consectetur est minus, repellendus quasi dolore. Reprehenderit porro voluptatem vero quia minus necessitatibus tempora delectus error at, iure quibusdam quam alias aliquam dolore ipsam reiciendis distinctio deleniti similique quaerat vel. Tenetur, fugiat magni ad molestias fuga quasi, veniam dolore, ea facere nobis suscipit. Natus, voluptates cum, illum perspiciatis error recusandae animi veniam eaque explicabo ratione commodi porro dolorem. Consequuntur quisquam reprehenderit molestias porro magnam dignissimos ducimus autem exercitationem, adipisci est!
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat ipsum animi iure rerum tenetur blanditiis, perspiciatis sed, molestias itaque error illo ullam saepe sequi dolorum reiciendis quam corrupti quos quisquam nemo dicta aliquam culpa. Nam repellendus recusandae veniam suscipit minima odit laborum animi dolorum quibusdam error accusamus architecto maiores, fuga dolor est quas aliquid voluptatem natus molestiae, voluptas quod fugiat voluptate eum. Impedit numquam mollitia voluptates aspernatur dolor cum inventore architecto ratione. Ducimus suscipit nisi optio alias dolor voluptates ipsum natus, placeat unde, tenetur aliquam, temporibus quis neque cum magni vitae vero? Repudiandae, dolorem! Error suscipit maxime nemo? Mollitia eveniet dolore repellat eos animi fugit cupiditate unde praesentium sunt laudantium dignissimos aperiam ipsum, dolor, ea cumque qui excepturi ad voluptate rerum. Reprehenderit iste esse omnis vero voluptates. Neque soluta at consectetur est minus, repellendus quasi dolore. Reprehenderit porro voluptatem vero quia minus necessitatibus tempora delectus error at, iure quibusdam quam alias aliquam dolore ipsam reiciendis distinctio deleniti similique quaerat vel. Tenetur, fugiat magni ad molestias fuga quasi, veniam dolore, ea facere nobis suscipit. Natus, voluptates cum, illum perspiciatis error recusandae animi veniam eaque explicabo ratione commodi porro dolorem. Consequuntur quisquam reprehenderit molestias porro magnam dignissimos ducimus autem exercitationem, adipisci est!
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugiat ipsum animi iure rerum tenetur blanditiis, perspiciatis sed, molestias itaque error illo ullam saepe sequi dolorum reiciendis quam corrupti quos quisquam nemo dicta aliquam culpa. Nam repellendus recusandae veniam suscipit minima odit laborum animi dolorum quibusdam error accusamus architecto maiores, fuga dolor est quas aliquid voluptatem natus molestiae, voluptas quod fugiat voluptate eum. Impedit numquam mollitia voluptates aspernatur dolor cum inventore architecto ratione. Ducimus suscipit nisi optio alias dolor voluptates ipsum natus, placeat unde, tenetur aliquam, temporibus quis neque cum magni vitae vero? Repudiandae, dolorem! Error suscipit maxime nemo? Mollitia eveniet dolore repellat eos animi fugit cupiditate unde praesentium sunt laudantium dignissimos aperiam ipsum, dolor, ea cumque qui excepturi ad voluptate rerum. Reprehenderit iste esse omnis vero voluptates. Neque soluta at consectetur est minus, repellendus quasi dolore. Reprehenderit porro voluptatem vero quia minus necessitatibus tempora delectus error at, iure quibusdam quam alias aliquam dolore ipsam reiciendis distinctio deleniti similique quaerat vel. Tenetur, fugiat magni ad molestias fuga quasi, veniam dolore, ea facere nobis suscipit. Natus, voluptates cum, illum perspiciatis error recusandae animi veniam eaque explicabo ratione commodi porro dolorem. Consequuntur quisquam reprehenderit molestias porro magnam dignissimos ducimus autem exercitationem, adipisci est!
      </p>
    </div>
  )
}

export default Internal
